version: '1.0'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=plazoleta
      - POSTGRES_USER=kenny
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysqluser:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=usermicroservice
      - MYSQL_USER=user
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 33061:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - PMA_HOST=mysqluser
    ports:
      - 8081:80